### PR TITLE
adding more choices to Positions

### PR DESCRIPTION
**Pull request by cxrodgers**
As discussed in https://github.com/safwanrahman/jobtalk_beta/issues/1 and taken from the positions in the mockup pdf

### CODE REVIEW

**Comment by safwanrahman** [comment]
I think you need to create a migration as well!

**Comment by cxrodgers** [comment]
Oh yeah, you are right of course, sorry about that. I don't have it set up on my end to run "heroku local" and test modifications yet which is why I missed this. I will do that first and then fix this.

**Comment by cxrodgers** [comment]
Hi @safwanrahman does this look okay to you? It works for me locally. I think you will need to migrate the heroku database.

**Comment by safwanrahman** [comment]
@cxrodgers Cool. Thanks a lot!

**Pull request merged**
